# Generated by Django 5.0.9 on 2024-10-21 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_user_mobile_number_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='0000000000', max_length=15, unique=True, verbose_name='Mobile Number'),
        ),
    ]
